@startuml BYON Callhandling 0.1.0

title "BYON WEB RTC FLOW - Call handling v0.1.0"
autonumber "<font color=blue><b>[0]"

<style>
.audioStyle {
  arrow {
    LineColor red
    LineThickness 5
  }
}
.wsStyle { 
  arrow { 
    LineColor blue 
    LineThickness 5 
  } 
} 
</style>

'participant "Notification\nclient" as WebClient
participant "Web\nClient" as WebClient
'participant OAuth #LightGreen
participant "WebRTC\ngateway" as WebRTC_GW
participant "IMS\nNetwork" as IMS_Network
participant "Remote\nendpoint" as RemoteEndpoint

' --- Notification Channel 
group Notification Channel 
note right WebClient
  Create notification channel for
  incoming updates. Valid options:
  - Websocket channel
  - PNS channel
end note

[-> WebClient: Launch app

WebClient -> WebRTC_GW: **POST /notificationchannel/{apiVersion}/channels** \n\
  Parameters:\n - authorization\n - transactionId\n - clientId\n\
  Body:\n - channelType\n - channelURL\n - resourceURL\n - callbackURL

activate WebClient #LightGray

WebRTC_GW -> WebClient: **200 OK**\nBody:\n\
 - channelType\n - channelData\n - resourceURL\n - callbackURL\n - status

WebClient <-> WebRTC_GW <<wsStyle>>: Notification channel established
note right
  webSocketsdata->channelURL
  PNSChannelData->registrationToken
  --
  A PSN notification channel won't requiere
  a direct WS. It will reach the user device
  using another connection.
end note
end

' -------------------------------------------------------
' CALL TERMINATION - WebRTC device receives voice session
' -------------------------------------------------------

group CALL ORIGINATION

WebClient -> WebRTC_GW : **POST /vvoip/{apiVersion}/sessions** \n\
  Parameters:\n - authorization\n - transactionId\n - clientId\n\
  Body:\n\
  - originatorAddress \n\
  - receiverAddress : callbackURL \n\
  - status \n\
  - offer : sdp_WebRTC

activate WebClient

WebRTC_GW -> IMS_Network: **SIP INVITE** \n\
From: originatorAddress \n\
To: receiverAddress \n\
sdp_inital_offer

IMS_Network -> RemoteEndpoint: **SIP INVITE** \n\
From: originatorAddress \n\
To: receiverAddress \n\
sdp_inital_offer

RemoteEndpoint -> IMS_Network: 100 Trying
IMS_Network -> WebRTC_GW: 100 Trying 
WebRTC_GW -> WebClient: **201 Created session** \n\
  Body: \n\
  - originatorAddress \n\
  - receiverAddress \n\
  - status : "Initial" \n\
  - resourceURL

...
RemoteEndpoint -> IMS_Network: **183 Session progress** \n\
sdp_provisonal_response
IMS_Network -> WebRTC_GW: **183 Session progress** \n\
sdp_provisonal_response
WebRTC_GW --> WebClient: JSON vvoipsession status \n\
  - status: **InProgress** \n\
  - answer: sdp_provisonal_response
note right of WebClient #LightSalmon
Event docs pending
Issue #15
end note
note right of WebClient
Assuming info from
GET /vvoip
end note
WebClient --> WebRTC_GW: JSON Ack
note right #LightSalmon: Not defined\nMaybe a PUT?
WebRTC_GW ->IMS_Network: PRACK
IMS_Network -> RemoteEndpoint: PRACK
RemoteEndpoint -> IMS_Network: 200 OK (PRACK)
IMS_Network -> WebRTC_GW: 200 OK (PRACK)

WebClient <[#purple]-> WebRTC_GW: DTLS Handshake
WebClient <[#purple]-> WebRTC_GW: ICE Connectivity Check

RemoteEndpoint ->IMS_Network: 180 Ringing
IMS_Network -> WebRTC_GW: 180 Ringing
WebRTC_GW --> WebClient: JSON vvoipsession status\n\
  - status: **Ringing**
WebClient --> WebRTC_GW: JSON Ack
note right #LightSalmon
  Not defined, maybe a PUT? Seems not
  really necesary, since the WebRTC_GW
  is not doing nothing with this message.
end note

...

RemoteEndpoint -> IMS_Network: 200 OK (INVITE)
IMS_Network -> WebRTC_GW: 200 OK (INVITE)
WebRTC_GW --> WebClient: JSON vvoipsession status\n\
  - status: **Connected**
WebClient --> WebRTC_GW: JSON Ack
note right #LightSalmon: Not defined\nMaybe a PUT?
WebRTC_GW -> IMS_Network: ACK (200 Ok)
IMS_Network -> RemoteEndpoint: ACK (200 Ok)

WebClient <--> WebRTC_GW <<audioStyle>>: DTLS-SRTP
WebRTC_GW <--> RemoteEndpoint <<audioStyle>>: RTP/SRTP

...

[-> WebClient: Hangup
WebClient -> WebRTC_GW: **DELETE /vvoip/{userId}/sessions/{sessionId}**. \n Parameters: \n·transactionId \n·clientId \n·sessionId
WebRTC_GW -> IMS_Network: BYE
IMS_Network -> RemoteEndpoint: BYE

RemoteEndpoint -> IMS_Network: 200 OK (BYE)
IMS_Network -> WebRTC_GW: 200 OK (BYE)
WebRTC_GW -> WebClient: 200 OK

deactivate WebClient
deactivate WebClient

end

' -------------------------------------------------------
' CALL TERMINATION - WebRTC device receives voice session
' -------------------------------------------------------

group CALL TERMINATION

[-> WebClient: Launch app
WebClient <-> WebRTC_GW: **POST /racm/session**
activate WebClient #LightGray
WebClient <-> WebRTC_GW: **POST /notificationchannel/channels**
WebClient <-> WebRTC_GW <<wsStyle>>: Notification channel established

...

RemoteEndpoint -> IMS_Network: SIP INVITE [Offer 1]
'WebClient <-> WebRTC_GW: websocket Active
IMS_Network -> RemoteEndpoint: 100 Trying
IMS_Network -> WebRTC_GW: SIP INVITE [Offer 1]
WebRTC_GW -> IMS_Network: 100 Trying
'WebRTC_GW -> WebClient: JSON SessionInvitationNotification [sdpUNI offer 1]
WebRTC_GW --> WebClient: JSON vvoipsession status\n\
  - status: **Initial** \n\
  - offer: sdp
activate WebClient
'WebClient --> WebRTC_GW: JSON Ack
'note right #LightSalmon: Not defined\nMaybe a PUT?
note right of WebClient: Now call starts on the\ndevice side

' Initial WebClient setup
note right of WebClient
Local or no media provided
end note
WebClient -> WebRTC_GW: **PUT /vvoip/{userId}/sessions/{sessionId}/status**\n\
  Body: \n\
  - sdp \n\
  - status: In Progress
WebRTC_GW -> IMS_Network: 183 SessionInProgress [Answer1]
IMS_Network -> RemoteEndpoint: 183 SessionInProgress [Answer1]
WebRTC_GW ->   WebClient: 200 OK
RemoteEndpoint -> IMS_Network: PRACK
IMS_Network -> WebRTC_GW: PRACK
note left #LightSalmon: Maybe JSON event to WebClient missed?
WebRTC_GW -> IMS_Network: 200 OK (PRACK)
IMS_Network -> RemoteEndpoint: 200 OK (PRACK)

' WebClient Media discovery
note right of WebClient: Media ICE\ndiscovery
WebClient <[#purple]-> WebRTC_GW: DTLS Handshake
WebClient <[#purple]-> WebRTC_GW: ICE Connectivity Check

[<- WebClient : Ringing
WebClient -> WebRTC_GW: **PUT /vvoip/{userId}/sessions/{sessionId}/status**\n\
  Body: \n\
  - status: Ringing \n\
  - offer: sdp
WebRTC_GW ->   WebClient: 200 OK
WebRTC_GW -> IMS_Network: 180 Ringing
IMS_Network -> RemoteEndpoint: 180 Ringing

[-> WebClient : Answer]
WebClient -> WebRTC_GW: **PUT /vvoip/{userId}/sessions/{sessionId}/status**\n\
  Body: \n\
  - status: **Connected** \n\
  - offer: sdp \n\
  - asnwer: sdp
WebRTC_GW -> WebClient: 200 OK

WebRTC_GW -> IMS_Network: 200 OK
IMS_Network -> RemoteEndpoint: 200 Ok 
RemoteEndpoint -> IMS_Network: ACK
IMS_Network -> WebRTC_GW: ACK
WebRTC_GW --> WebClient: JSON vvoipsession status\n\
  - status: **Connected** \n\
  - offer: sdp \n\
  - answer: sdp

WebClient <--> WebRTC_GW <<audioStyle>>: DTLS-SRTP
WebRTC_GW <--> RemoteEndpoint <<audioStyle>>: RTP/SRTP

RemoteEndpoint -> IMS_Network: BYE
IMS_Network -> WebRTC_GW: BYE
WebRTC_GW --> WebClient: JSON vvoipsession status\n\
  - status: **Released** \n\
  - offer: sdp \n\
  - answer: sdp



WebClient -> WebRTC_GW: JSON Ack
note right #LightSalmon: Not defined\nMaybe a PUT?
deactivate WebClient
WebRTC_GW -> IMS_Network: 200 OK (BYE)
IMS_Network -> RemoteEndpoint: 200 OK (BYE)

end

@enduml
