@startuml BYON Callhandling

title "BYON WEB RTC FLOW - Call handling"
autonumber

participant WebClient
participant OAuth #LightGreen
participant "WebRTC\ngateway" as WebRTC_GW
participant "IMS\nNetwork" as IMS_Network
participant "Remote\nendpoint" as RemoteEndpoint


group Notification Channel 
WebClient <-> WebRTC_GW: Websocket Establish {apiRoot}/noitificationChannel/{apiVersion}/{deviceId}
WebRTC_GW -> WebClient: 200 OK
  note right
   webSocketsdata->channelURL
   PNSChannelData->registrationToken
  end note
end



group CALL ORIGINATION

WebClient -> WebRTC_GW : POST vvoip/{userId}/sessions} \n Parameters: \n ·transactionId \n ·clientId
WebRTC_GW -> IMS_Network: SIP INVITE
IMS_Network -> RemoteEndpoint: SIP INVITE
WebRTC_GW -> WebClient: 201 Created session
IMS_Network -> WebRTC_GW: 100 Trying 
RemoteEndpoint -> IMS_Network: 100 Trying

RemoteEndpoint -> IMS_Network: 183 session in porgress
IMS_Network -> WebRTC_GW: 183 session in porgress
WebRTC_GW -> WebClient: JSON (SessionStatusNotification)
WebClient -> WebRTC_GW: JSON Ack
WebRTC_GW ->IMS_Network: PRACK
IMS_Network -> RemoteEndpoint: PRACK
RemoteEndpoint -> IMS_Network: 200 OK (PRACK)
IMS_Network -> WebRTC_GW: 200 OK (PRACK)

WebClient <[#purple]-> WebRTC_GW: DTLS Handshake
WebClient <[#purple]-> WebRTC_GW: ICE Connectivity Check

RemoteEndpoint ->IMS_Network: 180 Ringing
IMS_Network -> WebRTC_GW: 180 Ringing
WebRTC_GW -> WebClient: JSON (SessionStatusNotificaiton)[Ringing]
WebClient -> WebRTC_GW: JSON Ack

RemoteEndpoint -> IMS_Network: 200 OK (INVITE)
IMS_Network -> WebRTC_GW: 200 OK (INVITE)
WebRTC_GW -> WebClient: JSON (SessionStatus) [connected]
WebClient -> WebRTC_GW: JSON Ack
WebRTC_GW -> IMS_Network: ACK (200 Ok)
IMS_Network -> RemoteEndpoint: ACK (200 Ok)

WebClient <--[#red]> WebRTC_GW: DTLS-SRTP
WebRTC_GW <--[#red]> RemoteEndpoint: RTP/SRTP

WebClient -> WebRTC_GW: DELETE vvoip/{userId}/sessions/{sessionId}. \n Parameters: \n·transactionId \n·clientId \n·sessionId
WebRTC_GW -> IMS_Network: BYE
IMS_Network -> RemoteEndpoint: BYE

RemoteEndpoint -> IMS_Network: 200 OK (BYE)
IMS_Network -> WebRTC_GW: 200 OK (BYE)
WebRTC_GW -> WebClient: 200 OK

end

group CALL TERMINATION

RemoteEndpoint -> IMS_Network: SIP INVITE [Offer 1]
WebClient <-> WebRTC_GW: websocket Active
IMS_Network -> RemoteEndpoint: 100 Trying
IMS_Network -> WebRTC_GW: SIP INVITE [Offer 1]
WebRTC_GW -> IMS_Network: 100 Trying
WebRTC_GW -> WebClient: JSON SessionInvitationNotification [sdpUNI offer 1]
WebClient -> WebRTC_GW: JSON Ack

WebClient -> WebRTC_GW: PUT [Inprogress] vvoip/{userId}/sessions/{sessionId}/status
WebRTC_GW -> IMS_Network: 183 SessionInProgress [Answer1]
IMS_Network -> RemoteEndpoint: 183 SessionInProgress [Answer1]
WebRTC_GW ->   WebClient: 200 OK
RemoteEndpoint -> IMS_Network: PRACK
IMS_Network -> WebRTC_GW: PRACK
WebRTC_GW -> IMS_Network: 200 OK (PRACK)
IMS_Network -> RemoteEndpoint: 200 OK (PRACK)

WebClient <[#purple]-> WebRTC_GW: DTLS Handshake
WebClient <[#purple]-> WebRTC_GW: ICE Connectivity Check

WebClient -> WebRTC_GW: PUT [Ringing] vvoip/{userId}/sessions/{sessionId}/status
WebRTC_GW -> WebClient: JSON Ack
WebRTC_GW -> IMS_Network: 180 Ringing
IMS_Network -> RemoteEndpoint: 180 Ringing

WebClient -> WebRTC_GW: PUT [answer] vvoip/{userId}/sessions/{sessionId}/status
WebRTC_GW -> WebClient: JSON Ack
WebRTC_GW -> IMS_Network: 200 OK
IMS_Network -> RemoteEndpoint: 200 Ok 
WebRTC_GW -> WebClient: JSON Ack
RemoteEndpoint -> IMS_Network: ACK
IMS_Network -> WebRTC_GW: ACK

WebClient <--[#red]> WebRTC_GW: DTLS-SRTP
WebRTC_GW <--[#red]> RemoteEndpoint: RTP/SRTP

RemoteEndpoint -> IMS_Network: BYE
IMS_Network -> WebRTC_GW: BYE
WebRTC_GW -> WebClient: JSON [Release]

WebClient -> WebRTC_GW: JSON Ack
WebRTC_GW -> IMS_Network: 200 OK (BYE)
IMS_Network -> RemoteEndpoint: 200 OK (BYE)

end

@enduml
