@startuml BYON Registration 0.1.0

title "BYON WEB RTC FLOW - Registration - 0.1.0"
autonumber "<font color=blue><b>[0]"


participant WebClient
participant OAuth #LightGreen
participant "WebRTC\ngateway" as WebRTC_GW
participant "IMS\nNetwork" as IMS_Network
participant "Remote\nendpoint" as RemoteEndpoint

' --- USER AUTHENTICATION and REGISTRATION
group USER AUTHENTICATION and REGISTRATION

WebClient -> OAuth: Authentication/refresh Token
OAuth -> WebClient: Access/refresh Token
WebClient -> WebRTC_GW: **POST /racm/{apiVersion}/session**\n\
 Parameteres:\n - authorization\n - transactionId\n - clientId\n\
 Body:\n - deviceId\n - notificationUri
WebRTC_GW <-> OAuth: Validate Auth-token
WebRTC_GW -> IMS_Network: **SIP REGISTER**\nFrom: IMPU\nTo:IMPU\nContact: WebRTC_GW
IMS_Network -> WebRTC_GW: 100 Trying
IMS_Network -> WebRTC_GW: 200 OK
WebRTC_GW -> WebClient: **200 OK**\nBody:\n - sessionID\n - clientid\n - resourceURL\n - channelURL\n - status
note over WebClient
  Registrations will be valid while
  auth-token is still valid.
end note

' --- Refreshing of registration
group Refreshing of registration
  note over WebRTC_GW
   Periodically refresh REGISTER
   while Auth-Token is still valid
  end note
  WebRTC_GW -> IMS_Network: SIP RE-REGISTER
  IMS_Network -> WebRTC_GW: 200 OK

else
note over WebClient
  Use **sessionId** from 200OK
  response body to POST racm/
  endpoint (session creation)
end note
WebClient -> WebRTC_GW: **PUT /racm/{apiVersion}/session/{sessionId}** \n\
 Parameters: \n - authorization\n - transactionId \n - clientId \n - sessionId

note right
  Auth-token refresh (after expiry)
end note
WebRTC_GW -> IMS_Network: SIP RE-REGISTER
IMS_Network -> WebRTC_GW: 200 OK
WebRTC_GW -> WebClient: **200 OK**\nBody:\n - sessionID\n - clientid\n - resourceURL\n - channelURL\n - status
end
end

' --- DE-REGISTRATION
group DE-REGISTRATION
note over WebClient
  Graceful logout
end note
WebClient -> WebRTC_GW: **DELETE /racm/{apiVersion}/session/{sessionId}** \n\
 Parameters: \n - authorization\n - transactionId\n - clientID
WebRTC_GW -> IMS_Network: SIP DE-REGISTER
IMS_Network -> WebRTC_GW: 200 OK
WebRTC_GW -> WebClient: **204 No content**
      note right: Clean up session context
note over WebClient
  Non-graceful logout will let the
  auth token to expire, leading to
  a SIP DE-REGISTRATION on the
  WebRTC gateway
end note
end 

@enduml
