@startuml

!pragma teoz true
autonumber 47 "<font color=blue><b>[0]"

<style>
.box {
  Margin 40
}
.audio{
  arrow {
    LineColor red
    LineThickness 5
  }
}
</style>

box Device 
  participant "Device\nApplication" as DA
end box

box Application Service Provider
  participant "Application\nServer" as AS
end box

box "Operator Network" #EEEEEE
  participant "Auth\nServer" as AUTH
  participant "WebRTC\nGateway" as WG
  participant "Telco\nNetwork" as TN
end box

box Device
  participant "Remote\nendpoint" as RE
end box

activate WG #LightSteelBlue
activate WG #LightSteelBlue
activate WG #LightSteelBlue
activate TN
activate RE
activate DA

== Call termination by call originator ==

DA -> AS: Call termination request

AS -> AUTH: GET /authorize
AS <-- AUTH: 302 Found\n(redirecting user agent)
DA <[#gray]-> AUTH: End user consent (e.g., ICM Auth Code Flow)
AS -> AUTH: POST /token
AS <-- AUTH: 200 OK

AS -[#red]> WG: **DELETE /webrtc-call-handling/{apiVersion}/sessions/{mediaSessionId}**

AUTH <- WG: POST /token/introspection
AUTH --> WG: 200 OK

AS <[#red]-- WG: **204 No content**

WG -> TN: **SIP BYE**
TN -> RE: SIP BYE

TN <- RE --: SIP 200 OK (BYE)
WG <- TN --: **SIP 200 OK (BYE)**

AS <[#red]- WG: **POST SINK_URL**
deactivate WG

DA <- AS
deactivate DA

AS --[#red]> WG: **204 No content**

@enduml