@startuml



!pragma teoz true
autonumber 20 "<font color=blue><b>[0]"

<style>
.box {
  Margin 40
}
.audio{
  arrow {
    LineColor red
    LineThickness 5
  }
}
</style>

box Device 
  participant "Device\nApplication" as DA
end box

participant "Notification\nRelay" as NR

box "Operator Network" #EEEEEE
  participant "OAuth\nServer" as AS
  box "WebRTC Gateway"
    participant "API Exposure\nFunction" as API
    participant "Notification\nService" as NS
  end box
  participant "Telco\nNetwork" as SS
end box

box Device
  participant "Remote\nendpoint" as RE
end box


activate DA
activate NR #LightSteelBlue
activate NS #LightSteelBlue
activate NS #LightSteelBlue


== UE registration (WebRTC registration) ==

DA -> AS: GET /token
DA <-- AS: 200 OK

DA -[#red]> API: **POST /webrtc-registration/v0.2/sessions**

AS <- API: POST /token/introspection
AS --> API++: 200 OK

note over API,SS
  phoneNumber (MSISDN) is retrieved
  based on access token or the deviceId, 
  part of the proivision and linked to 
  a subscriber.
end note

note over API,SS
  SIP Register is not required if the telco 
  network assigns specific number ranges to 
  the API Exposure Function and can route 
  calls for those numbers.
end note

opt
  API -> SS: **SIP REGISTER**
  activate SS #LightSteelBlue
  API <- SS: **200 OK**
end

DA <[#red]-- API--: **200 OK**

note over DA, NR
  Registrations can be valid when auth-token is expired. 
  When the registraion is expired, the event will be notitified 
  via the webrtc-events API
end note



== registration-ends subscription (WebRTC event subscription) ==


DA -> AS: GET /token
DA <-- AS: 200 OK

DA -[#red]> API: **POST /webrtc-events-suscription/{apiVersion}/subscriptions** 

AS <- API: POST /token/introspection
AS --> API++: 200 OK

API -> NS
activate NS #LightSteelBlue
API <-- NS

DA <[#red]-- API--: **201 Created**



@enduml