@startuml



!pragma teoz true
autonumber 1 "<font color=blue><b>[0]"

<style>
.box {
  Margin 40
}
.audio{
  arrow {
    LineColor red
    LineThickness 5
  }
}
</style>

box Device 
  participant "Device\nApplication" as DA
end box

participant "Notification\nRelay" as NR

box "Operator Network" #EEEEEE
  participant "OAuth\nServer" as AS
  box "WebRTC Gateway"
    participant "API Exposure\nFunction" as API
    participant "Notification\nService" as NS
  end box
  participant "Telco\nNetwork" as SS
end box

box Device
  participant "Remote\nendpoint" as RE
end box




[-> DA++: Launch app


DA -> NR: Start & Get sink URL ＆ notificationAuthToken
activate NR #LightSteelBlue
DA <-- NR: SINK_URL & NOTIFICATION_AUTH_TOKEN






== session-invitation susbcription (WebRTC event subscription) ==

DA -> AS: GET /token
DA <-- AS: 200 OK

DA -[#red]> API: **POST /webrtc-events-suscription/{apiVersion}/subscriptions**

AS <- API: POST /token/introspection
AS --> API++: 200 OK

API -> NS
activate NS #LightSteelBlue
API <-- NS

DA <[#red]-- API--: **201 Created**



== session-status susbcription (WebRTC event subscription) ==

DA -> AS: GET /token
DA <-- AS: 200 OK

DA -[#red]> API: **POST /webrtc-events-suscription/{apiVersion}/subscriptions**

AS <- API: POST /token/introspection
AS --> API++: 200 OK

API -> NS
activate NS #LightSteelBlue
API <-- NS

DA <[#red]-- API--: **201 Created**





@enduml